source 'https://api.berkshelf.com'

cookbook 'yum'
cookbook 'rvm', '~> 0.9.2'
cookbook 'sqlite', '~> 1.1.0'
cookbook 'mysql', '~> 5.3.6'
cookbook 'git'
cookbook 'build-essential'
cookbook 'nginx', '~> 2.7.4'
cookbook 'openssl', '~> 2.0.0'
cookbook 'nodejs', git:'https://github.com/mdxp/nodejs-cookbook.git'
